[package]
name = "kube"
version = "0.18.1"
description = "Kubernetes client in the style of client-go"
authors = [
  "clux <sszynrae@gmail.com>",
  "ynqa <un.pensiero.vano@gmail.com>",
]
license-file = "LICENSE"
repository = "https://github.com/clux/kube-rs"
readme = "README.md"
keywords = ["kubernetes", "reflector", "informer", "client-go", "client-rust"]
categories = ["web-programming::http-client"]
edition = "2018"

[dependencies]
base64 = "0.10.1"
chrono = "0.4.9"
dirs = "1.0.4"
failure = "0.1.6"
serde = "1.0.101"
serde_derive = "1.0.101"
serde_json = "1.0.41"
serde_yaml = "0.8.11"
openssl = "0.10.25"
http = "0.1.19"
url = "2.1.0"
log = "0.4.8"
time = "0.1.42"
either = "1.5.3"
tokio = { version = "=0.2.0-alpha.6", default-features = false, features = ["timer"] }

[features]
default = []
openapi = ["k8s-openapi"]

[dependencies.reqwest]
version = "0.10.0-alpha.1"
features = ["json"]
# TODO: rustls, gzip

[dev-dependencies]
tempfile = "3.1.0"
env_logger = "0.7.1"
tokio = { version = "=0.2.0-alpha.6" }
tokio-executor = "=0.2.0-alpha.6"

[dev-dependencies.k8s-openapi]
version = "0.6.0"
default-features = false
features = ["v1_15"]

[dependencies.k8s-openapi]
version = "0.6.0"
default-features = false
features = ["v1_15"]
optional = true
