# Release process :: cargo-release @ 0.18.0
#
# 0. (optional) cargo release minor ; verify readme + changelog bumped; then git reset --hard
# 1. PUBLISH_GRACE_SLEEP=20 cargo release minor --execute
# 1X.  - on failure: follow plan manually, cd into next dir to publish and run cargo publish
# 2. check consolidated commit
# 2X.  - on failure: git commit --amend and insert version
# 3. ./scripts/release-post.sh

# Reference
# https://github.com/sunng87/cargo-release/blob/master/docs/reference.md
# Dependencies in hooks; cargo-release, cargo-tree, sd, ripgrep

consolidate-commits = true
shared-version = true
pre-release-hook = ["../scripts/release-pre.sh"]
pre-release-commit-message = "release {{version}}"
# leave tagging + pushing to postrelease script (due to potential failures in 2 and 3)
push = false
tag = false
