overflow_delimited_expr = true
newline_style = "Unix"
merge_imports = true
reorder_impl_items = true
normalize_comments = true
fn_single_line = false
blank_lines_upper_bound = 2
ignore = [
  "src/api/*",
]
comment_width = 110
max_width = 110
inline_attribute_width = 80
