[package]
name = "examples"
version = "0.1.0"
authors = [
  "clux <sszynrae@gmail.com>",
  "Teo Klestrup RÃ¶ijezon <teo@nullable.se>",
]
publish = false
edition = "2018"

[features]
default = ["native-tls"]
native-tls = ["reqwest/native-tls", "kube/native-tls", "kube-runtime/native-tls"]
rustls-tls = ["reqwest/rustls-tls", "kube/rustls-tls", "kube-runtime/rustls-tls"]

[dev-dependencies]
anyhow = "1.0.31"
env_logger = "0.7.1"
futures = "0.3.5"
kube = { path = "../kube", version = "^0.39.0", default-features = false, features = ["derive"] }
kube-runtime = { path = "../kube-runtime", version = "^0.39.0", default-features = false }
k8s-openapi = { version = "0.9.0", features = ["v1_18"], default-features = false }
log = "0.4.8"
serde = { version = "1.0.111", features = ["derive"] }
serde_json = "1.0.55"
serde_yaml = "0.8.12"
tokio = { version = "0.2.21", features = ["full"] }
color-eyre = "0.5.0"
snafu = { version = "0.6.8", features = ["futures"] }
# Some Api::delete methods use Either
either = "1.5.3"
# Some configuration tweaking require reqwest atm
reqwest = { version = "0.10.6", default-features = false, features = ["json", "gzip", "stream"] }

[[example]]
name = "configmapgen_controller"
path = "configmapgen_controller.rs"

[[example]]
name = "configmap_watcher"
path = "configmap_watcher.rs"

[[example]]
name = "configmap_reflector"
path = "configmap_reflector.rs"

[[example]]
name = "crd_api"
path = "crd_api.rs"

[[example]]
name = "crd_apply"
path = "crd_apply.rs"

[[example]]
name = "crd_derive"
path = "crd_derive.rs"

[[example]]
name = "crd_reflector"
path = "crd_reflector.rs"

[[example]]
name = "deployment_reflector"
path = "deployment_reflector.rs"

[[example]]
name = "dynamic_api"
path = "dynamic_api.rs"

[[example]]
name = "event_watcher"
path = "event_watcher.rs"

[[example]]
name = "job_api"
path = "job_api.rs"

[[example]]
name = "log_stream"
path = "log_stream.rs"

[[example]]
name = "multi_watcher"
path = "multi_watcher.rs"

[[example]]
name = "pod_api"
path = "pod_api.rs"

[[example]]
name = "proxy"
path = "proxy.rs"

[[example]]
name = "pod_reflector"
path = "pod_reflector.rs"

[[example]]
name = "pod_watcher"
path = "pod_watcher.rs"

[[example]]
name = "node_reflector"
path = "node_reflector.rs"

[[example]]
name = "node_watcher"
path = "node_watcher.rs"

[[example]]
name = "secret_reflector"
path = "secret_reflector.rs"
