[package]
name = "examples"
version = "0.1.0"
authors = [
  "clux <sszynrae@gmail.com>",
  "Teo Klestrup RÃ¶ijezon <teo@nullable.se>",
  "kazk <kazk.dev@gmail.com>",
]
publish = false
edition = "2018"

[features]
default = ["native-tls", "schema", "kubederive", "ws"]
kubederive = ["kube/derive"] # by default import kube-derive with its default features
schema = ["kube-derive/schema"] # crd_derive_no_schema shows how to opt out
native-tls = ["kube/native-tls", "kube-runtime/native-tls"]
rustls-tls = ["kube/rustls-tls", "kube-runtime/rustls-tls"]
ws = ["kube/ws"]

[dev-dependencies]
anyhow = "1.0.37"
env_logger = "0.8.2"
futures = "0.3.8"
kube = { path = "../kube", version = "^0.54.0", default-features = false, features = ["admission"] }
kube-derive = { path = "../kube-derive", version = "^0.54.0", default-features = false } # only needed to opt out of schema
kube-runtime = { path = "../kube-runtime", version = "^0.54.0", default-features = false }
kube-core = { path = "../kube-core", version = "^0.54.0", default-features = false }
k8s-openapi = { version = "0.11.0", features = ["v1_20"], default-features = false }
log = "0.4.11"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
serde_yaml = "0.8.17"
tokio = { version = "1.0.1", features = ["full"] }
color-eyre = "0.5.10"
snafu = { version = "0.6.10", features = ["futures"] }
# Some Api::delete methods use Either
either = "1.6.1"
schemars = "0.8.0"
static_assertions = "1.1.0"
tar = "0.4.32"
tracing = "0.1"
tracing-subscriber = "0.2"
warp = { version = "0.3", features = ["tls"] }
http = "0.2.3"
json-patch = "0.2.6"

[[example]]
name = "configmapgen_controller"
path = "configmapgen_controller.rs"

[[example]]
name = "configmap_watcher"
path = "configmap_watcher.rs"

[[example]]
name = "configmap_reflector"
path = "configmap_reflector.rs"

[[example]]
name = "crd_api"
path = "crd_api.rs"

[[example]]
name = "crd_apply"
path = "crd_apply.rs"

[[example]]
name = "crd_derive"
path = "crd_derive.rs"

[[example]]
name = "crd_derive_schema"
path = "crd_derive_schema.rs"

[[example]] # run this without --no-default-features --features="native-tls"
name = "crd_derive_no_schema"
path = "crd_derive_no_schema.rs"

[[example]]
name = "crd_reflector"
path = "crd_reflector.rs"

[[example]]
name = "deployment_reflector"
path = "deployment_reflector.rs"

[[example]]
name = "dynamic_api"
path = "dynamic_api.rs"

[[example]]
name = "dynamic_pod"
path = "dynamic_pod.rs"

[[example]]
name = "event_watcher"
path = "event_watcher.rs"

[[example]]
name = "job_api"
path = "job_api.rs"

[[example]]
name = "log_stream"
path = "log_stream.rs"

[[example]]
name = "multi_watcher"
path = "multi_watcher.rs"

[[example]]
name = "pod_api"
path = "pod_api.rs"

[[example]]
name = "pod_cp"
path = "pod_cp.rs"

[[example]]
name = "pod_attach"
path = "pod_attach.rs"

[[example]]
name = "pod_exec"
path = "pod_exec.rs"

[[example]]
name = "pod_evict"
path = "pod_evict.rs"

[[example]]
name = "pod_shell"
path = "pod_shell.rs"

[[example]]
name = "pod_reflector"
path = "pod_reflector.rs"

[[example]]
name = "pod_watcher"
path = "pod_watcher.rs"

[[example]]
name = "node_reflector"
path = "node_reflector.rs"

[[example]]
name = "node_watcher"
path = "node_watcher.rs"

[[example]]
name = "dynamic_watcher"
path = "dynamic_watcher.rs"

[[example]]
name = "secret_reflector"
path = "secret_reflector.rs"

[[example]]
name = "admission_controller"
path = "admission_controller.rs"

[dependencies]
tokio-util = "0.6.0"
