[package]
name = "kube-core"
description = "Kube shared types, traits and client-less behavior"
version = "0.54.0"
authors = [
  "clux <sszynrae@gmail.com>",
  "kazk <kazk.dev@gmail.com>",
]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/clux/kube-rs"
readme = "../README.md"

[features]
ws = []
admission = ["json-patch"]
jsonpatch = ["json-patch"]

[dependencies]
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
thiserror = "1.0.23"
once_cell = "1.7.2"
url = "2.2.0"
log = "0.4.11"
http = "0.2.2"
json-patch = { version = "0.2.6", optional = true }

[dependencies.k8s-openapi]
version = "0.11.0"
default-features = false
features = []

[dev-dependencies.k8s-openapi]
version = "0.11.0"
default-features = false
features = ["v1_20"]

[dev-dependencies]
kube = { path = "../kube", version = "<1.0.0, >=0.53.0" }
