[package]
name = "kube-core"
description = "Kube shared types, traits and client-less behavior"
version = "0.62.0"
authors = [
  "clux <sszynrae@gmail.com>",
  "kazk <kazk.dev@gmail.com>",
]
edition = "2021"
rust-version = "1.56"
license = "Apache-2.0"
repository = "https://github.com/kube-rs/kube-rs"
readme = "../README.md"

[features]
ws = []
admission = ["json-patch"]
jsonpatch = ["json-patch"]
deprecated-crd-v1beta1 = []

[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
thiserror = "1.0.29"
form_urlencoded = "1.0.1"
http = "0.2.5"
json-patch = { version = "0.2.6", optional = true }
once_cell = "1.8.0"
chrono = "0.4.19"

[dependencies.k8s-openapi]
version = "0.13.1"
default-features = false
features = []

[dev-dependencies.k8s-openapi]
version = "0.13.1"
default-features = false
features = ["v1_22"]

[dev-dependencies]
kube = { path = "../kube", version = "<1.0.0, >=0.53.0" }
