[package]
name = "kube-derive"
description = "Custom derives for the kube kubernetes crates"
version = "0.50.1"
authors = [
  "clux <sszynrae@gmail.com>",
  "kazk <kazk.dev@gmail.com>",
]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/clux/kube-rs"
readme = "../README.md"

[dependencies]
proc-macro2 = "1.0.24"
quote = "1.0.8"
syn = { version = "1.0.57", features = ["extra-traits"] }
Inflector = "0.11.4"
serde_json = "1.0.61"
darling = "0.12.1"

[lib]
proc-macro = true

[features]
default = ["schema"]
schema = []

[dev-dependencies]
serde = { version = "1.0.118", features = ["derive"] }
serde_yaml = "0.8.17"
k8s-openapi = { version = "0.11.0", default-features = false, features = ["v1_20"] }
schemars = { version = "0.8.0", features = ["chrono"] }
chrono = "0.4.19"
trybuild = "1.0"
