[package]
name = "kube-derive"
description = "Custom derives for the kube kubernetes crates"
version = "0.75.0"
authors = [
  "clux <sszynrae@gmail.com>",
  "kazk <kazk.dev@gmail.com>",
]
edition = "2021"
rust-version = "1.60.0"
license = "Apache-2.0"
repository = "https://github.com/kube-rs/kube"
readme = "../README.md"

[dependencies]
proc-macro2 = "1.0.29"
quote = "1.0.10"
syn = { version = "1.0.80", features = ["extra-traits"] }
serde_json = "1.0.68"
darling = "0.14.0"

[lib]
proc-macro = true

[dev-dependencies]
serde = { version = "1.0.130", features = ["derive"] }
serde_yaml = "0.8.21"
kube = { path = "../kube", default-features = false, version = "<1.0.0, >=0.61.0", features = ["derive"] }
k8s-openapi = { version = "0.16.0", default-features = false, features = ["v1_25"] }
schemars = { version = "0.8.6", features = ["chrono"] }
validator = { version = "0.16.0", features = ["derive"] }
chrono = { version = "0.4.19", default-features = false }
trybuild = "1.0.48"
assert-json-diff = "2.0.2"
